version: "2"
authtoken: 354MCxudKoGRubEaNVQawAuXwuP_4C8xDneqi8M6YaG8xJcsg

tunnels:
  backend:
    addr: backend:8000
    proto: http
    inspect: true

web_addr: 0.0.0.0:4040

log_level: info
log_format: logfmt
log: stdout
