version: "2"
authtoken: ${NGROK_AUTHTOKEN}

tunnels:
  backend:
    addr: backend:8000
    proto: http
    inspect: true
    # Usar el dominio reservado si está disponible
    # Si no, ngrok generará un dominio aleatorio
    # domain: "denver-unbrooded-miley.ngrok-free.dev"

web_addr: 0.0.0.0:4040

log_level: info
log_format: logfmt
log: stdout
